from aiogram.dispatcher.filters.state import State,StatesGroup



class Admin_(StatesGroup):
    add_new_cod = State()
    add_movie_poster = State()
    add_movie_trailer = State()
    add_movie_description = State()
    add_movie_file_mode = State()
    add_movie_file = State()
    add_category_name = State()
    add_subcategory_name = State()
    add_subcategory_file = State()
    delete_movie = State()
    edit_movie_select = State()
    edit_movie_menu = State()
    edit_movie_title = State()
    edit_movie_description = State()
    edit_movie_trailer = State()
    edit_categories_menu = State()
    edit_categories_delete = State()
    edit_torrents_menu = State()
    edit_torrents_delete = State()
    add_torrent_name = State()
    add_torrent_file = State()
    send_ = State()
    add_channel_link = State()
    add_channel = State()
    delete_channel = State()
    stats_user_lookup = State()