"""Interactive Docker deployment shared by Windows and Linux. Python stdlib only."""

import argparse
import getpass
import os
import re
import shutil
import subprocess
from pathlib import Path

try:
    from .deploy_storage import snapshot
except ImportError:
    from deploy_storage import snapshot

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".deploy.env"
MARKER = ROOT / "runtime" / "docker-local-api.ready"


def run(*args):
    subprocess.run(list(args), cwd=ROOT, check=True)


def compose(*args):
    run("docker", "compose", "--env-file", str(ENV), *args)


def domain_name(value):
    value = value.strip().lower()
    if not value:
        return ""
    if (
        len(value) > 253
        or "." not in value
        or not all(re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", label) for label in value.split("."))
    ):
        raise ValueError("Enter a domain such as kino.example.com, without https:// or a path")
    return value


def settings_text(api_id, api_hash, domain):
    if not api_id.isdecimal() or not 0 < int(api_id) < 2**31:
        raise ValueError("api_id must be a positive Telegram application ID")
    if not re.fullmatch(r"[a-fA-F0-9]{32}", api_hash):
        raise ValueError("api_hash must contain 32 hexadecimal characters")
    domain = domain_name(domain)
    return (
        "# Generated by setup. Docker Compose reads this file explicitly.\n"
        f"TELEGRAM_API_ID={api_id}\nTELEGRAM_API_HASH={api_hash}\n"
        f"WEB_DOMAIN={domain}\n"
        f"WEB_PUBLIC_URL={'https://' + domain if domain else 'http://127.0.0.1:8088'}\n"
        f"COMPOSE_PROFILES={'https' if domain else ''}\n"
        "UPLOAD_QUOTA_BYTES=20000000000\nTMDB_API_KEY=\nTMDB_USE_DOH=1\n"
    )


def read_api_hash():
    visible = False
    while True:
        raw = (
            input("Telegram api_hash (VISIBLE in this terminal; paste then Enter): ")
            if visible
            else getpass.getpass("Telegram api_hash (hidden): ")
        )
        # Only strip surrounding copy/paste decorations, never repair the key itself.
        value = raw.strip().strip("\ufeff\u200b").strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1].strip()
        if re.fullmatch(r"[a-fA-F0-9]{32}", value):
            return value
        print(
            f"Received {len(value)} characters; expected 32 characters from 0-9, a-f. "
            "Copy the API hash field, not the bot token. The key is not printed."
        )
        choice = (
            input(
                "Enter V for visible paste (key will appear on screen), "
                "Enter to retry hidden input, or Q to stop: "
            )
            .strip()
            .lower()
        )
        if choice == "q":
            raise ValueError("API hash entry cancelled. Settings were not saved.")
        visible = choice == "v"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="Rebuild using saved settings; no cloud logout")
    args = parser.parse_args()
    if not shutil.which("docker"):
        raise ValueError(
            "Install Docker Engine + Compose on Linux, or Docker Desktop (Linux containers / WSL 2) on Windows."
        )
    try:
        platform = subprocess.check_output(
            ["docker", "info", "--format", "{{.OSType}}"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.PIPE,
            timeout=30,
        ).strip()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        if os.name == "nt":
            message = (
                "Docker CLI is installed, but Docker Engine is unavailable. "
                "Open Docker Desktop from Start and wait until the engine is running, "
                "then run setup.ps1 again. If Desktop is not installed, install it with "
                "the WSL 2 backend: https://docs.docker.com/desktop/setup/install/windows-install/ . "
                "Check: docker info. ExecutionPolicy Bypass does not fix this error."
            )
        else:
            message = (
                "Docker Engine is unavailable. Start the Docker service "
                "(usually: sudo systemctl start docker), check user permissions and "
                "the selected Docker context. Check: docker info."
            )
        raise ValueError(message) from error
    if platform != "linux":
        raise ValueError("Switch Docker Desktop to Linux containers (WSL 2), then retry.")
    run("docker", "compose", "version")
    if args.update and not MARKER.exists():
        raise ValueError("Complete first-time setup before using --update.")
    if not ENV.exists():
        if args.update:
            raise ValueError(".deploy.env is missing. Restore saved deployment settings.")
        print("Get api_id and api_hash from my.telegram.org. Bot token stays in data/config.py.")
        values = settings_text(
            input("Telegram api_id: ").strip(),
            read_api_hash(),
            input("HTTPS domain (empty = localhost / SSH tunnel): "),
        )
        fd = os.open(ENV, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as output:
            output.write(values)
    compose("config", "--quiet")  # Validate without printing secrets.
    print("Building images. The first Telegram API build can take a long time.")
    compose("build")
    if not MARKER.exists():
        print("Stop the old bot (including any systemd service/container) before continuing.")
        if input("Type STOPPED when the old bot is stopped: ").strip() != "STOPPED":
            raise ValueError("No services switched. Re-run setup after stopping the old bot.")
    compose("stop", "bot")
    seed = None
    if not MARKER.exists():
        source = input(
            "Existing SQLite path [bot.sqlite], or NEW for a new catalog / existing Docker volume: "
        ).strip()
        if source != "NEW":
            source = Path(source or "bot.sqlite").expanduser()
            if not source.is_absolute():
                source = ROOT / source
            if not source.is_file():
                raise ValueError("Source database not found. Setup stopped; no empty catalog substituted.")
            seed = ROOT / "runtime" / "setup-seed.sqlite"
            snapshot(source, seed)
            print("Consistent source backup saved to runtime/setup-seed.sqlite.")
    storage_args = ["run", "--rm", "--no-deps", "--user", "0"]
    if seed:
        storage_args += ["--volume", f"{seed.as_posix()}:/seed.sqlite:ro"]
    storage_args += ["bot", "python", "tools/deploy_storage.py"]
    if seed:
        storage_args += ["--source", "/seed.sqlite"]
    compose(*storage_args)
    compose("up", "-d", "--wait", "--wait-timeout", "300", "bot-api")
    if not MARKER.exists():
        print("Cloud -> local migration requires logOut. Cloud return is blocked for 10 minutes afterwards.")
        answer = input(
            "Type LOGOUT to migrate, or LOCAL only if this bot is already on this local API server: "
        ).strip()
        if answer == "LOGOUT":
            compose("run", "--rm", "--no-deps", "bot", "python", "tools/logout_cloud.py", "--execute")
        elif answer != "LOCAL":
            raise ValueError("Bot was not started. Re-run setup to finish migration.")
        MARKER.parent.mkdir(parents=True, exist_ok=True)
        MARKER.write_text("Cloud migration completed. Do not repeat logOut on updates.\n", encoding="utf-8")
    compose("up", "-d", "--wait", "--wait-timeout", "300")
    print("Services started. Send /web to the bot as administrator.")
    print("Saved settings: .deploy.env. Update: setup.sh --update / setup.ps1 --update.")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"Setup stopped: {error}")
        raise SystemExit(1)
    except (KeyboardInterrupt, EOFError):
        print("\nSetup interrupted. Saved settings and volumes were preserved.")
        raise SystemExit(1)
